@startuml
   class HeatHandler{
       - zkClient:CuratorFramework
       + sequenceId: Long
       hand():void
   }

   class ChildrenListener{
       + heatHandler HeatHandler
       + startHandler():void
   }

   class ZkClientFactory{
      - zkServer: String
      - nameSpace: String
      + create():CuratorFramework
   }

   class ChildrenFactory{
       zkClient:CuratorFramework
       watchNode: String
      + create(): PathChildrenCache
   }


  ChildrenFactory-->ChildrenListener
  ChildrenListener->HeatHandler








@enduml